# Generated by Django 2.2.26 on 2022-03-08 15:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
